### ISSUE TITLE
Problems with MHC regions

### ISSUE THREAD

**Issue by cro280** [adriaan-vd-graaf/mrlink2#1]
Hoi Adriaan,

Thank you for sharing this extremely well put-together MR method; in terms of getting it running it's the easiest program I've come across.

When trying to run an analysis within part of the MHC region (region I'm interested going from chr6 30,316,328 - 31,577,220) the program is not able to identify any regions here. Do you have any advice in terms of parameters I can change to help in detection of a region? 

Also in line 938 of mr_link_2_standalone.py, the clumping p-threshold is set to 5-6 (not 5e-6). Dunno if this has any overall impact but thought I'd let you know. 

Thanks again and best wishes,
Cato Romero

**Comment by adriaan-vd-graaf** [comment]
Hi Cato,

First of all, thank you for trying out the program and for your kind words. Very nice to read.

I've added a flag to the program to be able to include your region, however please be very careful in it's application. Due to the long range LD within the HLA region I'm afraid that you will find the results to be more significant than one would otherwise expect. Please include the `--no_exclude_hla` flag to your command, and you'll be able to analyse the region of interest.

Regarding the typo, that's a very good find! Thanks! Luckily it will not mess up the MR-link 2 inference, as the clumping is only done to find an initial starting point for the optimization. And the optimizer will naturally move away from it.  So no worries about any previous results. I've fixed it regardless. 

Thanks again for using MR-link 2 and if you have any questions or comments, please do reach out!  

Bedankt!
Adriaan
